[ Community ] 성장/커뮤니티 페이지 좌측 사이드바 구현
NOW-SOPT-CDSP-TEAM-WEB4/Notefolio-Client pull request #34
Opened 2024-05-18 06:44 UTC by sinji2102

## 🔥 Related Issues

- close #30 

## ✅ 작업 내용

- [ ] 성장/커뮤니티 페이지 좌측 사이드바 구현

## 📸 스크린샷 / GIF / Link
- 전체 화면 
![image](https://github.com/NOW-SOPT-CDSP-TEAM-WEB4/Notefolio-Client/assets/66528589/2386d7df-ecb3-4458-b125-286360c7c028)

- 사이드바
![image](https://github.com/NOW-SOPT-CDSP-TEAM-WEB4/Notefolio-Client/assets/66528589/676eca58-a1c1-4138-a7b8-bb9261d79976)

- 토글 Open
![image](https://github.com/NOW-SOPT-CDSP-TEAM-WEB4/Notefolio-Client/assets/66528589/66d311ec-ede3-4dfb-93d0-0e69a3b126fc)

## 📌 이슈 사항
노트폴리오 페이지에는 토글 오픈 시 애니메이션이 적용되어 있으나, 현재 적용되어 있지 않은 상태입니다!

2024-05-19 02:57 UTC, jungwoo3490 requested changes
전체적으로 map을 많이 사용했는데, map을 돌리는 요소는 반복되어서 사용된다는 의미이기도 하니까, map을 돌리는 하위 요소를 공통 컴포넌트로 뽑아주면 코드가 더 깔끔해지겠다는 생각이 드네요!!

구현 고생했고 리뷰 남겨둔 것들 반영해주면 좋을 것 같습니닷!! 고생했어요!!!!!

2024-05-19 02:57 UTC, jungwoo3490 commented on src/components/Community/CommunitySidebar.tsx
> +  ];
요런 것들은 제 PR 참고해서 constants 파일로 분리해보는 것도 좋을 것 같아요!!!

2024-05-19 02:57 UTC, jungwoo3490 commented on src/components/Community/CommunitySidebar.tsx
> +              value={idx}
value prop에 idx값을 직접적으로 주었는데 idx 값은 가변적인 값이기 때문에 추후 순서가 바뀌게 되면 같이 변경될 위험이 있어요!!

혹시 value prop이 어디에 사용되는 친구일까요.....?

2024-05-19 02:57 UTC, jungwoo3490 commented on src/components/Community/CommunitySidebar.tsx
> +                <ToggleBtn type="button" className={"btn" + (toggleOpen == true ? " active" : "")} />
Styled-Component는 prop을 넘겨서 style 처리를 할 수 있어요!! 이렇게 하는 방식보다 toggleOpen을 prop으로 넘겨주는 방식이 CSS-in-JS 방식에 더 맞는 것 같아서 이렇게 바꿔보는건 어떨까요~?
```suggestion
                <ToggleBtn type="button" $toggleOpen={toggleOpen} />
```

이렇게 prop으로 내려주면

```tsx
const ToggleBtn = styled(IcArrowdownSm)`
  position: absolute;
  right: 0;
  bottom: 1.9rem;
  transform: ${({ $toggleOpen }) => $toggleOpen && "rotate(180deg)"};
`;
```

이렇게 해줄 수 있어요!!

2024-05-19 02:57 UTC, jungwoo3490 commented on src/components/Community/CommunitySidebar.tsx
> +              className={"btn" + (idx == btnActive ? " active" : "")}
여기도!!! 밑에 설명한 방법을 참고해서 바꿔보면 좋을 것 같습니다아!!!

2024-05-19 02:57 UTC, jungwoo3490 commented on src/components/Community/CommunitySidebar.tsx
> +                })}
요 부분을
```suggestion
                {commuityCategory.map((item) => (
                    <DropdownBtn type="button" key={item}>
                      {item}
                    </DropdownBtn>
                  )
                )}
```

이렇게 해줄 수 있습니다!!

2024-05-19 02:57 UTC, jungwoo3490 commented on src/components/Community/CommunitySidebar.tsx
> +        })}
이 부분도
```suggestion
        {outLinkCategory.map((item) => 
          (
            <OutLinkBtn type="button" key={item.content}>
              <OutLinkImg>{item.element}</OutLinkImg>
              {item.content}
            </OutLinkBtn>
          )
        )}
```

이렇게 해줄 수 있습니다!!!

2024-05-19 16:57 UTC, KIMGEONHWI approved these changes
고생했어 신지!!

2024-05-19 16:57 UTC, KIMGEONHWI commented on src/components/Community/CommunitySidebar.tsx
> +                <ToggleBtn type="button" className={"btn" + (toggleOpen == true ? " active" : "")} />
저도 이 방법이 더욱 좋아보여요!

2024-05-20 18:22 UTC, jungwoo3490 approved these changes
리뷰 반영 굿!! 머지해도 될 것 같습니당!! 신지 고생했어요!!! 👍🏻👍🏻👍🏻

2024-05-20 18:22 UTC, jungwoo3490 commented on src/components/Community/CommunitySidebar.tsx
> +              {item.dropdown === true ? <ToggleBtn type="button" $toggleOpen={toggleOpen} /> : null}
요거 단락평가 이용하면 ` {item.dropdown === true && <ToggleBtn type="button" $toggleOpen={toggleOpen} />}` 이렇게 구현할 수도 있으니 참고!!!

2024-05-20 18:35 UTC, merged