[ Home ] 홈 페이지 캐러셀 구현
NOW-SOPT-CDSP-TEAM-WEB4/Notefolio-Client pull request #36
Opened 2024-05-18 14:36 UTC by KIMGEONHWI

## 🔥 Related Issues

- close #33 

## ✅ 작업 내용

- [x] 홈 페이지 내 캐러셀 구현

## 📸 스크린샷 / GIF / Link

https://github.com/NOW-SOPT-CDSP-TEAM-WEB4/Notefolio-Client/assets/66071954/da391335-b391-433f-8f64-3ec95e0c8d90

## 📌 이슈 사항
**useState 훅**을 사용하여 offset 상태를 관리. offset은 이미지 컨테이너의 위치를 조정하는 데 사용.
**handleLeftClick 함수**는 왼쪽 버튼을 클릭했을 때 호출되며, offset 값을 증가시켜 이미지를 오른쪽으로 이동시킴.
**handleRightClick 함수**는 오른쪽 버튼을 클릭했을 때 호출되며, offset 값을 감소시켜 이미지를 왼쪽으로 이동시킴.
```typescript
function CarouselContainer() {
  const [offset, setOffset] = useState(0);
  const imageCount = 4;
  const imageWidth = 23;

  const handleLeftClick = () => {
    setOffset((prevOffset) => Math.max(prevOffset + imageWidth, 0));
  };

  const handleRightClick = () => {
    setOffset((prevOffset) => Math.max(prevOffset - imageWidth, -(imageCount - 1) * imageWidth));
  };
```
**버튼 위치 구현**
CarouselContainerWrapper에 position: relative;를 주고, 
각각의 버튼에 position: absolute;을 주고 top, left(or rigiht)값을 지정해줌.

## ✍ 궁금한 것

2024-05-19 02:23 UTC, jungwoo3490 requested changes
지금 보면 왼쪽 끝에 도달했을 때 좌측이 비어보이는데 노트폴리오 홈페이지에서는 무한 슬라이드처럼 맨 처음 이미지 왼쪽에 다시 맨 마지막 이미지가 이어지더라구요!!

요거 한 번 도전해보고 리소스가 크다 싶으면 기&디랑 논의한 다음에 맨 좌측일 때는 좌측으로 가기 버튼 숨기기, 맨 우측일때는 오른쪽으로 가기 버튼 숨기기 정도...? 라도 해주는 게 UX 측면에서 좋지 않을까 하는 생각입니다!!

2024-05-19 02:23 UTC, jungwoo3490 commented on src/assets/svg/ic_cs_four.svg
이런 파일들은 사실 보면 svg 보다 img에 가까운 애들이라 png 파일로 뽑아주는 게 더 좋을 것 같다는 생각임다!!

2024-05-19 02:23 UTC, jungwoo3490 commented on src/components/Home/CarouselContainer.tsx
> +}
요 부분은 type 폴더에 별도로 분리해줘도 좋을 것 같아요!!

2024-05-20 19:10 UTC, KIMGEONHWI commented on src/assets/svg/ic_cs_four.svg
png파일로 뽑아서 사용하도록 수정했습니다!

2024-05-20 19:14 UTC, closed without merging